[package]
name = "download-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
reqwest = { version = "0.12.24", features = ["blocking"]}

[[bin]]
name = "dlm"
path = "src/main.rs"
