[book]
title = "The Rust Download Book"
authors = ["Vinay Keerthi"]
language = "en"
description = "A book on writing Rust code to download. What, you ask? *Everything*"

[output.html]
admonitions = true
git-repository-url = "https://github.com/stonecharioteer/download-manager"
git-repository-icon = "fab-github"
